apiVersion: apps/v1
kind: Service
metadata:
  name: webbalancer
spec:
  selector:
    app: asblog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: loadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: asblog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asblog
  template:
    metadata:
      labels:
        app: asblog
    spec:
      containers:
      - name: mywebsite
        image: aseada/asblog_repo:tagname
        ports:
        - containerPort: 80
